"""Cross-SDK Empirical Compatibility & Adversarial Invariant Test: TypeScript buyerSdkTs <-> Python."""

import json
import subprocess
import pytest
from razoragentMesh.packages.buyerSdkPy.razoragent_buyer_sdk.agentKeyManager import (
    AgentKeyManager as PyAgentKeyManager,
    canonicalizeJson as pyCanonicalizeJson,
    computeSha256Digest as pyComputeSha256Digest,
)
from razoragentMesh.packages.buyerSdkPy.razoragent_buyer_sdk.agentMandateBuilder import (
    computeMandateHash as pyComputeMandateHash,
    createCartMandate as pyCreateCartMandate,
    createExecutionMandate as pyCreateExecutionMandate,
    createIntentMandate as pyCreateIntentMandate,
    validateMandateInvariants as pyValidateMandateInvariants,
)
from razoragentMesh.packages.buyerSdkPy.razoragent_buyer_sdk.models import (
    CartItemSchema,
    TaxBreakdownSchema,
)
from razoragentMesh.packages.buyerSdkPy.razoragent_buyer_sdk.powSolver import (
    solvePoWChallenge as pySolvePoWChallenge,
    verifyPoWSolution as pyVerifyPoWSolution,
)
from razoragentMesh.packages.mandateEngine.crypto.ed25519Verifier import Ed25519Verifier as PyEd25519Verifier


def _runNodeScript(script: str) -> str:
    """Executes a Node.js ES module script in buyerSdkTs directory via stdin to preserve UTF-8."""
    import os
    targetCwd = "packages/buyerSdkTs" if os.path.isdir("packages/buyerSdkTs") else "razoragentMesh/packages/buyerSdkTs"
    res = subprocess.run(
        ["node", "--import", "tsx", "--input-type=module"],
        input=script.encode("utf-8"),
        cwd=targetCwd,
        capture_output=True,
        check=False,
    )
    if res.returncode != 0:
        raise RuntimeError(f"Node execution failed (code {res.returncode}):\nSTDOUT: {res.stdout.decode('utf-8')}\nSTDERR: {res.stderr.decode('utf-8')}")
    return res.stdout.decode("utf-8").strip()



def testTsSigningPythonVerification() -> None:
    """Verify that Ed25519 detached signatures generated by TypeScript SDK verify in Python PyNaCl."""
    nodeScript = """
import { AgentKeyManager } from './src/agentKeyManager.js';
const km = AgentKeyManager.generate();
const payload = { mandateId: 'M-TS-001', amountPaise: 495600, currency: 'INR', active: true };
const signatureHex = km.signPayload(payload);
console.log(JSON.stringify({
    publicKeyHex: km.getPublicKeyHex(),
    agentDid: km.getAgentDid(),
    payload,
    signatureHex
}));
"""
    output = _runNodeScript(nodeScript)
    data = json.loads(output)
    pubKeyHex = data["publicKeyHex"]
    payload = data["payload"]
    sigHex = data["signatureHex"]

    # Verify using Python PyNaCl verifier
    isValid = PyEd25519Verifier.verifyPayloadSignature(pubKeyHex, payload, sigHex, raiseOnFailure=False)
    assert isValid is True

    # Verify using Python AgentKeyManager
    isValidKm = PyAgentKeyManager.verifyPayloadSignature(pubKeyHex, payload, sigHex, raiseOnFailure=False)
    assert isValidKm is True


def testPythonSigningTsVerification() -> None:
    """Verify that Ed25519 detached signatures generated by Python SDK verify in TypeScript SDK."""
    pyKm = PyAgentKeyManager.generate()
    payload = {"cartId": "cart_py_001", "totalPaise": 250000, "items": [{"skuId": "SKU-A", "qty": 2}]}
    sigHex = pyKm.signPayload(payload)
    pubKeyHex = pyKm.getPublicKeyHex()

    nodeScript = f"""
import {{ AgentKeyManager }} from './src/agentKeyManager.js';
const km = AgentKeyManager.generate();
const payload = {json.dumps(payload)};
const sigHex = '{sigHex}';
const pubKeyHex = '{pubKeyHex}';
const isValid = km.verifyPayloadSignature(payload, sigHex, pubKeyHex);
console.log(JSON.stringify({{ isValid }}));
"""
    output = _runNodeScript(nodeScript)
    data = json.loads(output)
    assert data["isValid"] is True


def testJcsCanonicalizationCrossEquivalence() -> None:
    """Verify byte-for-byte identity of JCS canonical bytes and SHA-256 digests between TS and Python."""
    testCases = [
        {"zebra": 1, "apple": 2, "mango": 3},
        {"nested": {"b": 2, "a": 1}, "list": [{"z": 10, "y": 20}]},
        {"emptyObj": {}, "emptyList": [], "zero": 0, "negative": -100},
        {"unicode": "Razorpay ⚡ Autonomous Agent 🇮🇳", "status": "CONFIRMED"},
    ]

    for payload in testCases:
        pyBytes = pyCanonicalizeJson(payload)
        pyDigest = pyComputeSha256Digest(pyBytes)

        nodeScript = f"""
import {{ canonicalizeJsonString, computeSha256Digest }} from './src/jcsCanonicalizer.js';
const payload = {json.dumps(payload)};
const tsCanonical = canonicalizeJsonString(payload);
const tsDigest = computeSha256Digest(tsCanonical);
console.log(JSON.stringify({{ tsCanonical, tsDigest }}));
"""
        output = _runNodeScript(nodeScript)
        data = json.loads(output)
        assert data["tsCanonical"] == pyBytes.decode("utf-8")
        assert data["tsDigest"] == pyDigest


def testCrossMandateHashEquivalence() -> None:
    """Verify that Intent, Cart, and Execution mandates produce identical hashes across TS and Python."""
    fixedTs = 1700000000
    fixedNonce = "nonce_fixed_1234567890"

    # Intent Mandate
    intentDict = {
        "authorizedCategories": ["electronics"],
        "currency": "INR",
        "delegatedAgentDid": "did:agent:" + "1" * 64,
        "mandateId": "M-INTENT-001",
        "maxBudgetPaise": 500000,
        "nonce": fixedNonce,
        "singleTransactionLimitPaise": 500000,
        "timestamp": fixedTs,
        "upiCircleDelegationToken": "upi_tok_001",
        "userDid": "did:agent:" + "2" * 64,
        "validUntilTimestamp": fixedTs + 86400,
        "userSignature": "0" * 128,
    }

    pyHash = pyComputeMandateHash(intentDict)

    nodeScript = f"""
import {{ computeMandateHash }} from './src/agentMandateBuilder.js';
const intent = {json.dumps(intentDict)};
const tsHash = computeMandateHash(intent);
console.log(JSON.stringify({{ tsHash }}));
"""
    output = _runNodeScript(nodeScript)
    data = json.loads(output)
    assert data["tsHash"] == pyHash


def testCrossPowVerification() -> None:
    """Verify that PoW solutions solved in TS verify in Python, and vice versa."""
    challengeToken = "cross_pow_challenge_test_token_888"
    difficulty = 4

    # 1. TS solves -> Python verifies
    nodeScript = f"""
import {{ solvePowChallenge }} from './src/powSolver.js';
const solution = solvePowChallenge('{challengeToken}', {difficulty});
console.log(JSON.stringify(solution));
"""
    output = _runNodeScript(nodeScript)
    tsSolution = json.loads(output)
    pyValid = pyVerifyPoWSolution(challengeToken, tsSolution["nonce"], difficulty)
    assert pyValid is True

    # 2. Python solves -> TS verifies
    pyNonce = pySolvePoWChallenge(challengeToken, difficulty)
    nodeVerifyScript = f"""
import {{ verifyPowSolution }} from './src/powSolver.js';
const verifyResult = verifyPowSolution('{challengeToken}', {pyNonce}, {difficulty});
console.log(JSON.stringify(verifyResult));
"""
    verifyOutput = _runNodeScript(nodeVerifyScript)
    tsVerify = json.loads(verifyOutput)
    assert tsVerify["isValid"] is True
