"""Cross-SDK Empirical Compatibility & Adversarial Invariant Test: TypeScript buyerSdkTs <-> Python."""

import json
import os
import subprocess
from pathlib import Path

import pytest
from razoragentMesh.packages.buyerSdkPy.razoragent_buyer_sdk.agentKeyManager import (
    AgentKeyManager as PyAgentKeyManager,
    canonicalizeJson as pyCanonicalizeJson,
    computeSha256Digest as pyComputeSha256Digest,
)
from razoragentMesh.packages.buyerSdkPy.razoragent_buyer_sdk.agentMandateBuilder import (
    computeMandateHash as pyComputeMandateHash,
    createCartMandate as pyCreateCartMandate,
    createExecutionMandate as pyCreateExecutionMandate,
    createIntentMandate as pyCreateIntentMandate,
    validateMandateInvariants as pyValidateMandateInvariants,
)
from razoragentMesh.packages.buyerSdkPy.razoragent_buyer_sdk.models import (
    CartItemSchema,
    TaxBreakdownSchema,
)
from razoragentMesh.packages.buyerSdkPy.razoragent_buyer_sdk.powSolver import (
    solvePoWChallenge as pySolvePoWChallenge,
    verifyPoWSolution as pyVerifyPoWSolution,
)
from razoragentMesh.packages.mandateEngine.crypto.ed25519Verifier import Ed25519Verifier as PyEd25519Verifier
from razoragentMesh.packages.mandateEngine.verification.arithmeticEnclave import computeGstBreakdown

_fixturesDir = Path(__file__).parent / "fixtures"


def _resolvePackageCwd(packageName: str) -> str:
    """Locates a workspace package directory relative to either the repo root or its parent."""
    relative = f"packages/{packageName}"
    return relative if os.path.isdir(relative) else f"razoragentMesh/{relative}"


def _runNodeScript(script: str, package: str = "buyerSdkTs") -> str:
    """Executes a Node.js ES module script inside the given package directory via stdin, to preserve UTF-8."""
    res = subprocess.run(
        ["node", "--import", "tsx", "--input-type=module"],
        input=script.encode("utf-8"),
        cwd=_resolvePackageCwd(package),
        capture_output=True,
        check=False,
    )
    if res.returncode != 0:
        raise RuntimeError(f"Node execution failed (code {res.returncode}):\nSTDOUT: {res.stdout.decode('utf-8')}\nSTDERR: {res.stderr.decode('utf-8')}")
    return res.stdout.decode("utf-8").strip()



def testTsSigningPythonVerification() -> None:
    """Verify that Ed25519 detached signatures generated by TypeScript SDK verify in Python PyNaCl."""
    nodeScript = """
import { AgentKeyManager } from './src/agentKeyManager.js';
const km = AgentKeyManager.generate();
const payload = { mandateId: 'M-TS-001', amountPaise: 495600, currency: 'INR', active: true };
const signatureHex = km.signPayload(payload);
console.log(JSON.stringify({
    publicKeyHex: km.getPublicKeyHex(),
    agentDid: km.getAgentDid(),
    payload,
    signatureHex
}));
"""
    output = _runNodeScript(nodeScript)
    data = json.loads(output)
    pubKeyHex = data["publicKeyHex"]
    payload = data["payload"]
    sigHex = data["signatureHex"]

    # Verify using Python PyNaCl verifier
    isValid = PyEd25519Verifier.verifyPayloadSignature(pubKeyHex, payload, sigHex, raiseOnFailure=False)
    assert isValid is True

    # Verify using Python AgentKeyManager
    isValidKm = PyAgentKeyManager.verifyPayloadSignature(pubKeyHex, payload, sigHex, raiseOnFailure=False)
    assert isValidKm is True


def testPythonSigningTsVerification() -> None:
    """Verify that Ed25519 detached signatures generated by Python SDK verify in TypeScript SDK."""
    pyKm = PyAgentKeyManager.generate()
    payload = {"cartId": "cart_py_001", "totalPaise": 250000, "items": [{"skuId": "SKU-A", "qty": 2}]}
    sigHex = pyKm.signPayload(payload)
    pubKeyHex = pyKm.getPublicKeyHex()

    nodeScript = f"""
import {{ AgentKeyManager }} from './src/agentKeyManager.js';
const km = AgentKeyManager.generate();
const payload = {json.dumps(payload)};
const sigHex = '{sigHex}';
const pubKeyHex = '{pubKeyHex}';
const isValid = km.verifyPayloadSignature(payload, sigHex, pubKeyHex);
console.log(JSON.stringify({{ isValid }}));
"""
    output = _runNodeScript(nodeScript)
    data = json.loads(output)
    assert data["isValid"] is True


def testJcsCanonicalizationCrossEquivalence() -> None:
    """Verify byte-for-byte identity of JCS canonical bytes and SHA-256 digests between TS and Python.

    The astral-plane case below is the one that actually exercises RFC 8785's UTF-16
    key-ordering rule: Python's native string sort is by Unicode code point, so a key
    made of an astral character (U+1F600, encoded as a UTF-16 surrogate pair) and a key
    made of a high-BMP character (U+FF01) sort in OPPOSITE order between naive Python
    sorting and JS/RFC 8785 UTF-16 sorting. Every other case here uses plain ASCII or
    BMP keys, where code-point order and UTF-16 order agree -- so it alone would pass
    even with the ordering bug this test is meant to catch.
    """
    testCases = [
        {"zebra": 1, "apple": 2, "mango": 3},
        {"nested": {"b": 2, "a": 1}, "list": [{"z": 10, "y": 20}]},
        {"emptyObj": {}, "emptyList": [], "zero": 0, "negative": -100},
        {"unicode": "Razorpay ⚡ Autonomous Agent 🇮🇳", "status": "CONFIRMED"},
        {"\U0001F600": "astral-key", "！": "bmp-key", "zebra": "ascii-key"},
    ]

    for payload in testCases:
        pyBytes = pyCanonicalizeJson(payload)
        pyDigest = pyComputeSha256Digest(pyBytes)

        nodeScript = f"""
import {{ canonicalizeJsonString, computeSha256Digest }} from './src/jcsCanonicalizer.js';
const payload = {json.dumps(payload)};
const tsCanonical = canonicalizeJsonString(payload);
const tsDigest = computeSha256Digest(tsCanonical);
console.log(JSON.stringify({{ tsCanonical, tsDigest }}));
"""
        output = _runNodeScript(nodeScript)
        data = json.loads(output)
        assert data["tsCanonical"] == pyBytes.decode("utf-8")
        assert data["tsDigest"] == pyDigest


def testGstCrossLanguageEquivalence() -> None:
    """Verify the Python settlement enclave and the TypeScript MCP quoter compute byte-identical
    GST for every golden vector. This is the test that would have caught the two real bugs found in
    review: Python's percent-rate split going asymmetric on odd GST slabs, and a 1-paise total drift
    between the two languages' formulas -- both silent, because no prior test compared them directly."""
    vectors = json.loads((_fixturesDir / "gstGoldenVectors.json").read_text(encoding="utf-8"))["vectors"]

    for vector in vectors:
        pyResult = computeGstBreakdown(vector["taxablePaise"], vector["ratePercent"], isIntraState=vector["intraState"])
        assert pyResult.cgstPaise == vector["cgstPaise"]
        assert pyResult.sgstPaise == vector["sgstPaise"]
        assert pyResult.igstPaise == vector["igstPaise"]
        assert pyResult.totalTaxPaise == vector["totalTaxPaise"]
        if vector["intraState"]:
            assert pyResult.cgstPaise == pyResult.sgstPaise

    nodeScript = f"""
import {{ calculateGstBreakdown }} from './src/catalog/pricingEngine.js';
const vectors = {json.dumps(vectors)};
const results = vectors.map((v) => {{
    const merchantState = 'KA';
    const buyerState = v.intraState ? 'KA' : 'MH';
    return calculateGstBreakdown(v.taxablePaise, v.ratePercent, merchantState, buyerState);
}});
console.log(JSON.stringify(results));
"""
    output = _runNodeScript(nodeScript, package="mcpServer")
    tsResults = json.loads(output)

    assert len(tsResults) == len(vectors)
    for vector, tsResult in zip(vectors, tsResults):
        assert tsResult["cgstPaise"] == vector["cgstPaise"], vector
        assert tsResult["sgstPaise"] == vector["sgstPaise"], vector
        assert tsResult["igstPaise"] == vector["igstPaise"], vector
        assert tsResult["totalTaxPaise"] == vector["totalTaxPaise"], vector


def testCrossMandateHashEquivalence() -> None:
    """Verify that Intent, Cart, and Execution mandates produce identical hashes across TS and Python."""
    fixedTs = 1700000000
    fixedNonce = "nonce_fixed_1234567890"

    # Intent Mandate
    intentDict = {
        "authorizedCategories": ["electronics"],
        "currency": "INR",
        "delegatedAgentDid": "did:agent:" + "1" * 64,
        "mandateId": "M-INTENT-001",
        "maxBudgetPaise": 500000,
        "nonce": fixedNonce,
        "singleTransactionLimitPaise": 500000,
        "timestamp": fixedTs,
        "upiCircleDelegationToken": "upi_tok_001",
        "userDid": "did:agent:" + "2" * 64,
        "validUntilTimestamp": fixedTs + 86400,
        "userSignature": "0" * 128,
    }

    pyHash = pyComputeMandateHash(intentDict)

    nodeScript = f"""
import {{ computeMandateHash }} from './src/agentMandateBuilder.js';
const intent = {json.dumps(intentDict)};
const tsHash = computeMandateHash(intent);
console.log(JSON.stringify({{ tsHash }}));
"""
    output = _runNodeScript(nodeScript)
    data = json.loads(output)
    assert data["tsHash"] == pyHash


def testCrossPowVerification() -> None:
    """Verify that PoW solutions solved in TS verify in Python, and vice versa."""
    challengeToken = "cross_pow_challenge_test_token_888"
    difficulty = 4

    # 1. TS solves -> Python verifies
    nodeScript = f"""
import {{ solvePowChallenge }} from './src/powSolver.js';
const solution = solvePowChallenge('{challengeToken}', {difficulty});
console.log(JSON.stringify(solution));
"""
    output = _runNodeScript(nodeScript)
    tsSolution = json.loads(output)
    pyValid = pyVerifyPoWSolution(challengeToken, tsSolution["nonce"], difficulty)
    assert pyValid is True

    # 2. Python solves -> TS verifies
    pyNonce = pySolvePoWChallenge(challengeToken, difficulty)
    nodeVerifyScript = f"""
import {{ verifyPowSolution }} from './src/powSolver.js';
const verifyResult = verifyPowSolution('{challengeToken}', {pyNonce}, {difficulty});
console.log(JSON.stringify(verifyResult));
"""
    verifyOutput = _runNodeScript(nodeVerifyScript)
    tsVerify = json.loads(verifyOutput)
    assert tsVerify["isValid"] is True
