// Writes src/generated/docsManifest.ts from the frontmatter of docs/**/*.mdx.
//
// The sidebar is a client component, so it cannot read the filesystem; but the documentation
// section must still be derived from the documents themselves rather than hand-maintained. This
// bridges the two: one generated file, checked into git, regenerated by `npm run docs:manifest`,
// and guarded by a test that fails if it drifts from the directory.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { loadDocNavEntries } from "../src/lib/docsLoader.js";

const currentDirectory = path.dirname(fileURLToPath(import.meta.url));
const packageRoot = path.resolve(currentDirectory, "..");
const outputPath = path.join(packageRoot, "src", "generated", "docsManifest.ts");

const fileHeader = `// GENERATED FILE -- DO NOT EDIT BY HAND.
//
// Produced by scripts/generateDocsManifest.ts from the frontmatter of docs/**/*.mdx.
// Regenerate with: npm run docs:manifest
// A test (test/docsPipeline.test.ts) fails if this file no longer matches the docs directory,
// so a stale manifest cannot ship silently.

import type { DocNavEntry } from "@/types/docsTypes";
`;

export function renderManifest(entries: ReturnType<typeof loadDocNavEntries>): string {
  const body = JSON.stringify(entries, null, 2);
  return `${fileHeader}
export const docsManifest: readonly DocNavEntry[] = ${body};
`;
}

function main(): void {
  // The loader resolves the docs directory relative to cwd, so the generator must run from the
  // package root -- the same place `next build` runs from.
  process.chdir(packageRoot);

  const entries = loadDocNavEntries();
  if (entries.length === 0) {
    throw new Error("Refusing to write an empty docs manifest: no .mdx files were found");
  }

  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, renderManifest(entries), "utf-8");
  process.stdout.write(`Wrote ${entries.length} entries to ${path.relative(packageRoot, outputPath)}\n`);
}

main();
