// Writes src/generated/docsSearchIndex.ts from the sections of docs/**/*.mdx.
//
// Companion to generateDocsManifest.ts and generated by the same command. The search box is a
// client component and cannot read the filesystem, so the index has to be built ahead of time
// and checked in; a test compares it against a fresh scan so it cannot drift from the docs.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { buildDocsSearchIndex } from "../src/lib/docsSearchIndexBuilder.js";

const currentDirectory = path.dirname(fileURLToPath(import.meta.url));
const packageRoot = path.resolve(currentDirectory, "..");
const outputPath = path.join(packageRoot, "src", "generated", "docsSearchIndex.ts");
const bytesPerKilobyte = 1024;

const fileHeader = `// GENERATED FILE -- DO NOT EDIT BY HAND.
//
// Produced by scripts/generateDocsSearchIndex.ts from the sections of docs/**/*.mdx.
// Regenerate with: npm run docs:generate
// A test (test/docsSearch.test.ts) fails if this file no longer matches the docs directory,
// so a stale index cannot ship silently.

import type { DocSearchEntry } from "@/types/docsTypes";
`;

export function renderSearchIndex(entries: readonly unknown[]): string {
  return `${fileHeader}
export const docsSearchIndex: readonly DocSearchEntry[] = ${JSON.stringify(entries, null, 2)};
`;
}

function main(): void {
  // The loader resolves the docs directory relative to cwd, so the generator must run from the
  // package root -- the same place `next build` runs from.
  process.chdir(packageRoot);

  const entries = buildDocsSearchIndex();
  if (entries.length === 0) {
    throw new Error("Refusing to write an empty search index: no doc sections were found");
  }

  const contents = renderSearchIndex(entries);
  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, contents, "utf-8");

  // The index ships to the browser, so its size is reported on every regeneration rather than
  // left to be discovered in a bundle analysis later.
  const sizeKilobytes = (Buffer.byteLength(contents, "utf-8") / bytesPerKilobyte).toFixed(1);
  process.stdout.write(
    `Wrote ${entries.length} sections (${sizeKilobytes} kB) to ` +
      `${path.relative(packageRoot, outputPath)}\n`
  );
}

main();
