"""Layer 4: Cryptographic Settlement Core (mandateEngine)."""

from .constants.settlementConstants import (
    basisPointsDivisor,
    maxValidGstRate,
    minValidGstRate,
    paisePerRupee,
    percentDivisor,
    tcsCgstBasisPoints,
    tcsIgstBasisPoints,
    tcsRateBasisPoints,
    tcsSgstBasisPoints,
    validGstRates,
    zeroPaise,
)
from .settlement.settlementExceptions import (
    ArithmeticDriftException,
    ArithmeticEnclaveMismatchException,
    BudgetExceededViolation,
    CategoryNotAuthorizedException,
    FutureTimestampException,
    InvalidPincodeException,
    MandateEngineException,
    MandateExpiredException,
    MandateHashChainMismatchException,
    NonceReplayException,
    PaymentBlockedException,
    SettlementCompensationTriggeredException,
    SignatureVerificationFailedException,
    SingleTransactionLimitExceededException,
    TimestampExpiredException,
    WebhookSignatureVerificationException,
)
from .tax.stateCodeMapping import (
    deriveStateCodeFromPincode,
    pinPrefixToStateCode,
)
from .verification.arithmeticEnclave import (
    GstBreakdown,
    RouteSplitResult,
    SpendingCapResult,
    allocateCartDiscountConserved,
    allocate_cart_discount_conserved,
    calculateRouteSplits,
    calculate_gst,
    calculate_route_splits,
    computeCartSettlementTotal,
    computeGstBreakdown,
    computeLineItemTotal,
    computeTcsWithholding,
    computeTotalPaise,
    compute_cart_settlement_total,
    compute_line_item_total,
    compute_tcs_withholding,
    evaluateSpendingCap,
    evaluate_spending_cap,
    normalizeInrToPaise,
    normalize_inr_to_paise,
    splitBillConserved,
    split_bill_conserved,
    validateIntegerPaise,
    validate_integer_paise,
)
from .tax.gstrInvoiceEngine import (
    GstrInvoicePayload,
    GstrLineItem,
    generateGstrInvoice,
    isPlaceOfSupplyIntraState,
)
from .tax.gstrInvoiceHtmlRenderer import (
    formatPaiseToInr,
    renderGstrInvoiceHtml,
)
from .crypto.cryptoKeyUtils import (
    extractPublicKeyFromDid,
    formatDid,
    generateKeyPair,
)
from .crypto.nonceGenerator import (
    generateNonce,
    generateTimestampedNonce,
)
from .crypto.jcsCanonicalizer import (
    canonicalizeAndHash,
    canonicalizeJson,
    computeSha256Digest,
)
from .crypto.ed25519Verifier import Ed25519Verifier
from .crypto.ed25519Signer import Ed25519Signer
from .verification.budgetGate import validateBudgetGate
from .verification.signatureChainVerifier import (
    verifyMandateChain,
)
from .mandates.amendmentMandateSchema import AmendmentMandate
from .mandates.cartMandateSchema import (
    CartItemSchema,
    CartMandate,
    TaxBreakdownSchema,
)
from .mandates.executionMandateSchema import ExecutionMandate
from .mandates.intentMandateSchema import IntentMandate
from .mandates.mandateFactory import (
    computeMandateHash,
    createSignedAmendmentMandate,
    createSignedCartMandate,
    createSignedExecutionMandate,
    createSignedIntentMandate,
    verifyMandateHashChain,
)
from .nonce.nonceLedger import (
    NonceLedger,
    maxNtpDriftToleranceSeconds,
    minNtpDriftToleranceSeconds,
    nonceRedisKeyPrefix,
    nonceTtlSeconds,
)
from .telemetryEmitter import (
    TelemetryEventEmitter,
    TelemetryEventModel,
    globalTelemetryEmitter,
)
from .settlement.razorpayRouteClient import (
    PaymentCaptureResponse,
    RazorpayRouteClient,
    RouteTransferRequest,
    RouteTransferResponse,
    TransferReversalResponse,
)
from .settlement.splitManifestBuilder import (
    SplitTransferManifest,
    buildSplitManifest,
    defaultLogisticsAccount,
    defaultProtocolFeeAccount,
    defaultProtocolFeePaise,
)
from .settlement.twoPhaseCommitSaga import TwoPhaseCommitSaga
from .settlement.webhookVerifier import (
    computeWebhookSignature,
    verifyRazorpayWebhookSignature,
)
from .settlement.settlementOrchestrator import (
    SettlementOrchestrator,
    SettlementResult,
)
from .config import (
    MandateEngineSettings,
    defaultMandateSettings,
    getMandateEngineSettings,
)
from .mandateApp import (
    ExecuteSettlementRequest,
    ExecuteSettlementRequestSchema,
    createMandateApp,
    mandateApp,
    mandateAppLifespan,
    mandateEnginePort,
)

__all__ = [
    "AmendmentMandate",
    "ArithmeticDriftException",
    "ArithmeticEnclaveMismatchException",
    "BudgetExceededViolation",
    "CartItemSchema",
    "CartMandate",
    "CategoryNotAuthorizedException",
    "Ed25519Signer",
    "Ed25519Verifier",
    "ExecuteSettlementRequest",
    "ExecuteSettlementRequestSchema",
    "ExecutionMandate",
    "FutureTimestampException",
    "GstrInvoicePayload",
    "GstrLineItem",
    "GstBreakdown",
    "IntentMandate",
    "InvalidPincodeException",
    "MandateEngineException",
    "MandateEngineSettings",
    "MandateExpiredException",
    "MandateHashChainMismatchException",
    "NonceLedger",
    "NonceReplayException",
    "PaymentBlockedException",
    "PaymentCaptureResponse",
    "RazorpayRouteClient",
    "RouteSplitResult",
    "RouteTransferRequest",
    "RouteTransferResponse",
    "SettlementCompensationTriggeredException",
    "SettlementOrchestrator",
    "SettlementResult",
    "SignatureVerificationFailedException",
    "SingleTransactionLimitExceededException",
    "SpendingCapResult",
    "SplitTransferManifest",
    "TaxBreakdownSchema",
    "TelemetryEventEmitter",
    "TelemetryEventModel",
    "TimestampExpiredException",
    "TransferReversalResponse",
    "TwoPhaseCommitSaga",
    "WebhookSignatureVerificationException",
    "allocateCartDiscountConserved",
    "allocate_cart_discount_conserved",
    "basisPointsDivisor",
    "buildSplitManifest",
    "calculateRouteSplits",
    "calculate_gst",
    "calculate_route_splits",
    "canonicalizeAndHash",
    "canonicalizeJson",
    "computeCartSettlementTotal",
    "computeGstBreakdown",
    "computeLineItemTotal",
    "computeTcsWithholding",
    "computeTotalPaise",
    "compute_cart_settlement_total",
    "compute_line_item_total",
    "compute_tcs_withholding",
    "evaluateSpendingCap",
    "evaluate_spending_cap",
    "normalizeInrToPaise",
    "normalize_inr_to_paise",
    "splitBillConserved",
    "split_bill_conserved",
    "validateBudgetGate",
    "validateIntegerPaise",
    "validate_integer_paise",
    "computeMandateHash",
    "computeSha256Digest",
    "computeWebhookSignature",
    "createMandateApp",
    "createSignedAmendmentMandate",
    "createSignedCartMandate",
    "createSignedExecutionMandate",
    "createSignedIntentMandate",
    "defaultLogisticsAccount",
    "defaultMandateSettings",
    "defaultProtocolFeeAccount",
    "defaultProtocolFeePaise",
    "deriveStateCodeFromPincode",
    "extractPublicKeyFromDid",
    "formatDid",
    "formatPaiseToInr",
    "generateGstrInvoice",
    "generateKeyPair",
    "generateNonce",
    "generateTimestampedNonce",
    "getMandateEngineSettings",
    "globalTelemetryEmitter",
    "isPlaceOfSupplyIntraState",
    "mandateApp",
    "mandateAppLifespan",
    "mandateEnginePort",
    "maxNtpDriftToleranceSeconds",
    "maxValidGstRate",
    "minNtpDriftToleranceSeconds",
    "minValidGstRate",
    "nonceRedisKeyPrefix",
    "nonceTtlSeconds",
    "paisePerRupee",
    "percentDivisor",
    "pinPrefixToStateCode",
    "renderGstrInvoiceHtml",
    "tcsCgstBasisPoints",
    "tcsIgstBasisPoints",
    "tcsRateBasisPoints",
    "tcsSgstBasisPoints",
    "validGstRates",
    "verifyMandateChain",
    "verifyMandateHashChain",
    "verifyRazorpayWebhookSignature",
    "zeroPaise",
]

